# Generated by Django 6.0.5 on 2026-07-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='level',
            field=models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid-Level'), ('senior', 'Senior')], default='mid', max_length=20),
        ),
    ]
